// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/team-direct-reports/ExpandableManagers.tsx": () => import("../components/mockups/team-direct-reports/ExpandableManagers.tsx")
};
